Deprecate SF Symbols recipes
autopkg/dataJAR-recipes pull request #396
Opened 2024-12-31 05:25 UTC by homebysix

This PR deprecates the version-specific SF Symbols recipes in this repo, which are not sufficiently distinct from other recipes in the AutoPkg org to warrant the extra maintenance they require. The deprecation notice points users to the SFSymbols recipes in foigus-recipes.

2024-12-31 09:53 UTC, paul-cossey requested changes
Happy for 2, 3 and 4 to be deprecated, but we have a need to get version specific downloads for 5 and 6. These can't be deprecated.

2024-12-31 22:42 UTC, homebysix commented
The ideal situation would be for a single recipe to be usable for both 5 and 6 with a simple override variable. [This change](https://github.com/autopkg/foigus-recipes/compare/master...homebysix:foigus-recipes:sfsymbols5?expand=1) would enable that on the foigus-recipes side. Would that meet your needs?

2024-12-31 23:04 UTC, macmule commented
As a rule, we typically prefer separate recipes per version without overriding an input var.

This makes it easier for us to maintain and deprecate.

A few times where we’ve had a more generic recipes we have then need to be amended for the later releases.. meaning we need to split.
________________________________
From: Elliot Jordan ***@***.***>
Sent: Tuesday, December 31, 2024 10:42:50 PM
To: autopkg/dataJAR-recipes ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [autopkg/dataJAR-recipes] Deprecate SF Symbols recipes (PR #396)


The ideal situation would be for a single recipe to be usable for both 5 and 6 with a simple override variable. This change<https://github.com/autopkg/foigus-recipes/compare/master...homebysix:foigus-recipes:sfsymbols5?expand=1> would enable that on the foigus-recipes side. Would that meet your needs?

—
Reply to this email directly, view it on GitHub<https://github.com/autopkg/dataJAR-recipes/pull/396#issuecomment-2566740842>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AASZZTTC3CD3S5ZF7PFLX5L2IMMWVAVCNFSM6AAAAABUNACNTWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRWG42DAOBUGI>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2025-01-06 09:23 UTC, paul-cossey commented
That change would work but as Ben said, while it's not a hard rule we do find it easier to maintain version specific recipes. 

Plus that change would also require additional admin effort for those that _only_ care about getting the latest version.  I think we're the exception here with needing both, and as such we're happy to maintain the version specific recipes.

2025-02-17 16:35 UTC, paul-cossey commented
I've deprecated 3 and 4, and updated the warning to 2. 

https://github.com/autopkg/dataJAR-recipes/commit/671f38f68d3f353010adb670135811afef26117a
https://github.com/autopkg/dataJAR-recipes/commit/351003ece42ab6caf041d33b7198628662822b78

I'll close this off now as new need to keep 5 and 6 as they are.

2025-02-17 16:35 UTC, closed without merging